### PR TITLE
Adjectives: Replace throbbing with thrumming.

### PR DESCRIPTION
**Pull request by ybakos**
The 'throbbing' adjective can be combined with 'shape' to result in
'throbbing shape,' which has sexual connotations and can be found
offensive in a business context.

Replace 'throbbing' with 'thrumming'. The word 'thrumming' means "make a continuous rhythmic humming sound."

### CODE REVIEW

**Comment by jakeNiemiec** [comment]
We got this as well.
image

Chances of getting this combo: 1 in 4096
Chances of upsetting stakeholders: 100%

Despite the dictionary definition, the term "throbbing" is commonly used to describe unpleasant things. Example:
image

@usmanbashir You can see how this clashes with the theme here. I recommend:
- trembling
- fluttering

**Comment by codered** [comment]
how do I get your change in my fork?

**Comment by ybakos** [comment]
@codered Just apply the change you see in https://github.com/usmanbashir/haikunator/pull/10/commits/83e8cb9f515e3e482dc8122f03eb0ce418d5a287

**Comment by codered** [comment]
Cools, i am taking all the merge pull requests into my repo. https://github.com/codered/haikunator

**Pull request merged**
